language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - sudo apt-get update
  - sudo apt-get install redis-server
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - django-admin.py test --settings=app_metrics.tests.settings app_metrics
env:
  - DJANGO>=1.11,<2.0
  - DJANGO>=2.0,<2.1
  - DJANGO>=2.1,<2.2
  - DJANGO>=2.2,<2.3
matrix:
  exclude:
    - python: 2.7
      env: DJANGO="Django>=2.0,<2.1"
    - python: 2.7
      env: DJANGO="Django>=2.1,<2.2"
    - python: 2.7
      env: DJANGO="Django>=2.2,<2.3"
